export default {
  dark: {
    theme_mode: "dark",
    bgBright: "#2c2f33",
    bg: "#2c2f33",
    border: "#313131",
    text: "#c3c3c3",
    shadow: "#313131",
    bgShadowLeft: "#25282b",
    bgShadowRight: "#33363b",
    insetShadowLeft: "#25282b",
    insetShadowRight: "#33363b",
    bgLeft: "#2f3237",
    bgRight: "#282a2e",
    linearGradLeft: "#2f3237",
    linearGradLeft: "#282a2e",
    icon: "#fff",
    menu: {
      text: "#f7f8fa",
      text_hover: "#edd92c",
      bg_active: "#edd92c",
      bg_active_border: "#e8401c",
      active_text: "#000",
    },
    input: {
      bg: "#2c2f33",
      text: "#f7f8fa",
      boxShadowLeft: "#1d1f22",
      boxShadowRight: "#3b3f44",
      dpActive: "#e6d11d",
    },
    label: {
      text: "#f7f8fa",
      errorText: "#ed4321",
    },
    radio: {
      bg: "#cbd1d8",
      text: "fff",
      bgHover: "#9faab7",
      bgChecked: "#e6d11d",
    },
    button: {
      bg: "#2c2f33",
      bgHover: "#9faab7",
      text: "#f7f8fa",
      boxShadowLeft: "#1d1f22",
      boxShadowRight: "#3b3f44",
      primary: "#e6d11d",
    },
  },
  light: {
    theme_mode: "light",
    bgBright: "#eceff2",
    bg: "#eceff2",
    border: "#e5e5e5",
    text: "#666",
    shadow: "#e9d5d81a",
    bgShadowLeft: "#c9cbce",
    bgShadowRight: "#ffffff",
    insetShadowLeft: "#d4d7da",
    insetShadowRight: "#ffffff",
    icon: "inherit",
    bgLeft: "#fffb3f",
    bgRight: "#e6d435",
    linearGradLeft: "#fdffff",
    linearGradLeft: "#d4d7da",
    menu: {
      text: "#666",
      text_hover: "#000",
      bg_active: "#edd92c",
      bg_active_border: "#e8401c",
      active_text: "#000",
    },
    input: {
      bg: "#ffffff",
      text: "#555",
      boxShadowLeft: "#d9d9d9",
      boxShadowRight: "#ffffff",
      dpActive: "#e6d11d",
    },
    label: {
      text: "#3C3C3F",
      errorText: "#ed4321",
    },
    radio: {
      bg: "#cbd1d8",
      text: "fff",
      bgHover: "#9faab7",
      bgChecked: "#e6d11d",
    },
    button: {
      bg: "#eceff2",
      bgHover: "#9faab7",
      text: "#000",
      boxShadowLeft: "#c9cbce",
      boxShadowRight: "#ffffff",
      primary: "#e6d11d",
    },
  },
};